name: Update README Daily

on:
  schedule:
    - cron: '0 10 * * *'  # Tous les jours à 10h UTC (tu peux changer l'heure)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Show Git Status and logs
      run: |
        git status
        git log --oneline -n 5

    - name: Update README
      run: |
        echo "🚀 Daily inspiration: $(date)" >> README.md

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "Daily update to README"
        git push
